--PEDIDOS_DET
DELETE FROM PEDIDOS_DET;

--PEDIDOS_CAB
DELETE FROM PEDIDOS_CAB;
DBCC CHECKIDENT (PEDIDOS_CAB, RESEED, 0)

--PRODUCTOS
DELETE FROM PRODUCTOS;
DBCC CHECKIDENT (PRODUCTOS, RESEED, 0)

--TELEFONOS
DELETE FROM TELEFONOS;

--DIRECCIONES
DELETE FROM DIRECCIONES;
DBCC CHECKIDENT (DIRECCIONES, RESEED, 0)

--USUARIOS
DELETE FROM USUARIOS;
DBCC CHECKIDENT (USUARIOS, RESEED, 0)

--TIPO_PRODUCTO
DELETE FROM TIPO_PRODUCTO;
DBCC CHECKIDENT (TIPO_PRODUCTO, RESEED, 0)

--MARCAS
DELETE FROM MARCAS;
DBCC CHECKIDENT (MARCAS, RESEED, 0)

--ESTADOS
DELETE FROM ESTADOS;
DBCC CHECKIDENT (ESTADOS, RESEED, 0)